version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /hmmer.wdl
     testParameterFiles:
       - /hmmscan.json
     filters:
       branches:
         - feature/test*
       tags:
         - /\d+\.\d+\.\d+/
