version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /hmmer.wdl
     testParameterFiles:
       - /hmmscan.json
       - /hmmsearch.json
     filters:
       branches:
         - master
         - develop
         - feature/**
       tags:
         - /\d+\.\d+\.\d+/
